variables:

# -----------------------------------------------------------------------------------------------------
# Blueprint: universal-artifact
#
# If you are not going to use all stages, as below, you can suppress them in your *-start.yml template
# by setting these optional parameters to true:
#
# suppressDV - Defaults to false, which does NOT suppress the Development stage deployment
# suppressPR - Defaults to false, which does NOT suppress the Production stage deployment
#
# Need help with the configuration?
#
# -VARIABLE ---------- VALUE ------
# *Active              true or false. To disable or hide a stage, set value to false.
# *EnvName             Contact Common Engineering 
#                      or see https://dev.azure.com/wcbbc/IT-App-Delivery/_environments
#                      Format: <portfolio>-<stage-name>-<stage-name-acronym>, for example
#                      assessments-development-dv
# *VmImage             ubuntu-latest, windows-latest, 
#                      or see https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted
# *other*              Contact your Delivery CSE.
# <portfolio>          Replace with your Azure DevOps portfolio name, matching ServiceNow.
#
# -----------------------------------------------------------------------------------------------------

# -----------------------------------------------------------------------------------------------------
# Continuous Integration #910188
- name:  ciStagePool
  value: 'Azure Pipelines'
- name:  ciStageVmImage
  value: 'ubuntu-latest'

# -----------------------------------------------------------------------------------------------------
# DEVelopment Stage
# -----------------------------------------------------------------------------------------------------
- name:  developmentStageActive
  value: true
- name:  developmentStageEnvName
  value: '<portfolio>-development-dv'
- name:  developmentStagePool
  value: 'Azure Pipelines'
- name:  developmentStageVmImage
  value: '<TBD>'
- name:  developmentStageFeedPublish
  value: '<TBD>'
- name:  developmentStagePackagePublish
  value: '<TBD>'

# -----------------------------------------------------------------------------------------------------
# System Test Stage
# -----------------------------------------------------------------------------------------------------
- name:  systemTestStageActive
  value: false
- name:  systemTestStageEnvName
  value: '<portfolio>-system-test-sy'
- name:  systemTestStagePool
  value: 'Azure Pipelines'
- name:  systemTestStageVmImage
  value: '<TBD>'
- name:  systemTestStageFeedPublish
  value: '<TBD>'
- name:  systemTestStagePackagePublish
  value: '<TBD>'

# -----------------------------------------------------------------------------------------------------
# Staging Stage
# -----------------------------------------------------------------------------------------------------
- name:  stagingStageActive
  value: false
- name:  stagingStageEnvName
  value: '<portfolio>-staging-st'
- name:  stagingStagePool
  value: 'Azure Pipelines'
- name:  stagingStageVmImage
  value: '<TBD>'
- name:  stagingStageFeedPublish
  value: '<TBD>'
- name:  stagingStagePackagePublish
  value: '<TBD>'

# -----------------------------------------------------------------------------------------------------
# PRODuction Test Stage
# -----------------------------------------------------------------------------------------------------
- name:  productionStageActive
  value: false
- name:  productionStageEnvName
  value: '<portfolio>-production-pr'
- name:  productionStagePool
  value: 'Azure Pipelines'
- name:  productionStageVmImage
  value: '<TBD>'
- name:  productionStageFeedPublish
  value: '<TBD>'
- name:  productionStagePackagePublish
  value: '<TBD>'

# -----------------------------------------------------------------------------------------------------
# Production Central Stage
# Introduced with version blueprintVersion 2.1.1
- name:  productionCanadaCentralStageActive
  value: false
- name:  productionCanadaCentralStageEnvName
  value: '<portfolio>-production-pr'
- name:  productionCanadaCentralStagePool
  value: 'Azure Pipelines'
- name:  productionCanadaCentralStageVmImage
  value: '<tbd>'
- name:  productionCanadaCentralStageFeedPublish
  value: '<TBD>'
- name:  productionCanadaCentralStagePackagePublish
  value: '<TBD>'

# -----------------------------------------------------------------------------------------------------
# Production East Stage
# Introduced with version blueprintVersion 2.1.1
- name:  productionCanadaEastStageActive
  value: false
- name:  productionCanadaEastStageEnvName
  value: '<portfolio>-production-pr'
- name:  productionCanadaEastStagePool
  value: 'Azure Pipelines'
- name:  productionCanadaEastStageVmImage
  value: '<tbd>'
- name:  productionCanadaEastStageFeedPublish
  value: '<TBD>'
- name:  productionCanadaEastStagePackagePublish
  value: '<TBD>'

# -----------------------------------------------------------------------------------------------------
# @@START: SKULL-AND-CROSS BONES AREA
# Introduced with version blueprintVersion 2.1.1
# Be very, very careful when making changes to the configuration below!
#
# Replace <portfolio> with your pipelines portfolioName setting
#
# -----------------------------------------------------------------------------------------------------

# -----------------------------------------------------------------------------------------------------
# Security Review Stage
- name:  securityReviewStageEnvName
  value: '<portfolio>-security-review-sr'
- name:  securityReviewStagePool
  value: 'Azure Pipelines'
- name:  securityReviewStageVmImage
  value: 'ubuntu-latest'

# -----------------------------------------------------------------------------------------------------
# Security Automation Stage #910188
- name:  securityAutomationStagePool
  value: 'Azure Pipelines'
- name:  securityAutomationStageVmImage
  value: 'ubuntu-latest'

# -----------------------------------------------------------------------------------------------------
# Quality Automation Stage #910188
- name:  qaAutomationStagePool
  value: 'Azure Pipelines'
- name:  qaAutomationStageVmImage
  value: 'ubuntu-latest'

# -----------------------------------------------------------------------------------------------------
# Pre-Prod Automation Stage #910188
- name:  preProdAutomationStagePool
  value: 'Azure Pipelines'
- name:  preProdAutomationStageVmImage
  value: 'ubuntu-latest'

# -----------------------------------------------------------------------------------------------------
# @@END: SKULL-AND-CROSS BONES AREA
# Introduced with version blueprintVersion 2.1.1
# -----------------------------------------------------------------------------------------------------