variables:

# -----------------------------------------------------------------------------------------------------
#
# If you are not going to use all stages, as below, you can suppress them by setting active to false.
#
# Need help with the configuration?
#
# -VARIABLE ---------- VALUE ------
# *Active              true or false. To disable or hide a stage, set value to false.
# *EnvName             See https://dev.azure.com/<__AzDO_ORG__>/<__AzDO_PROJECT__>/_environments
#                      Format: <portfolio>-<stage-name>-<stage-name-acronym>, for example
#                      assessments-development-dv
# *VmImage             ubuntu-latest, windows-latest, 
#                      or see https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted
#                      Leave leave empty for self-hosted agents
# *TestData            Sample configuration - replace with your own.
# <portfolio>          Replace with your Azure DevOps portfolio name, matching ServiceNow.
#
# -----------------------------------------------------------------------------------------------------

# -----------------------------------------------------------------------------------------------------
# Continuous Integration #910188
- name:  ciStagePool
  value: 'Azure Pipelines'
- name:  ciStageVmImage
  value: 'ubuntu-latest'

# -----------------------------------------------------------------------------------------------------
# Development Stage
- name:  developmentStageActive
  value: true
- name:  developmentStageEnvName
  value: '<portfolio>-development-dv'
- name:  developmentStagePool
  value: 'Azure Pipelines'
- name:  developmentStageVmImage
  value: 'ubuntu-latest'
- name:  developmentStageTestData
  value: 'Development Stage Test Data'

# -----------------------------------------------------------------------------------------------------
# System Test Stage
- name:  systemTestStageActive
  value: false
- name:  systemTestStageEnvName
  value: '<portfolio>-system-test-sy'
- name:  systemTestStagePool
  value: 'Azure Pipelines'
- name:  systemTestStageVmImage
  value: 'ubuntu-latest'
- name:  systemTestStageTestData
  value: 'System Test Stage Test Data'

# -----------------------------------------------------------------------------------------------------
# Staging Stage
- name:  stagingStageActive
  value: false
- name:  stagingStageEnvName
  value: '<portfolio>-staging-st'
- name:  stagingStagePool
  value: 'Azure Pipelines'
- name:  stagingStageVmImage
  value: 'ubuntu-latest'
- name:  stagingStageTestData
  value: 'Staging Stage Test Data'

# -----------------------------------------------------------------------------------------------------
# Production Stage
- name:  productionStageActive
  value: false
- name:  productionStageEnvName
  value: '<portfolio>-production-pr'
- name:  productionStagePool
  value: 'Azure Pipelines'
- name:  productionStageVmImage
  value: 'ubuntu-latest'
- name:  productionStageTestData
  value: 'Production Stage Test Data'

# -----------------------------------------------------------------------------------------------------
# Production Central Stage
# Introduced with version blueprintVersion 2.1.1
- name:  productionCanadaCentralStageActive
  value: false
- name:  productionCanadaCentralStageEnvName
  value: '<portfolio>-production-pr'
- name:  productionCanadaCentralStagePool
  value: 'Azure Pipelines'
- name:  productionCanadaCentralStageVmImage
  value: 'ubuntu-latest'
- name:  productionCanadaCentralStageTestData
  value: 'Production Canada Central Stage Test Data'

# -----------------------------------------------------------------------------------------------------
# Production East Stage
# Introduced with version blueprintVersion 2.1.1
- name:  productionCanadaEastStageActive
  value: false
- name:  productionCanadaEastStageEnvName
  value: '<portfolio>-production-pr'
- name:  productionCanadaEastStagePool
  value: 'Azure Pipelines'
- name:  productionCanadaEastStageVmImage
  value: 'ubuntu-latest'
- name:  productionCanadaEastStageTestData
  value: 'Production Canada East Stage Test Data'

# -----------------------------------------------------------------------------------------------------
# @@START: SKULL-AND-CROSS BONES AREA
# Introduced with version blueprintVersion 2.1.1
# Be very, very careful when making changes to the configuration below!
# -----------------------------------------------------------------------------------------------------

# -----------------------------------------------------------------------------------------------------
# Security Review Stage #910188
- name:  securityReviewStageEnvName
  value: '<portfolio>-security-review-sr'
- name:  securityReviewStagePool
  value: 'Azure Pipelines'
- name:  securityReviewStageVmImage
  value: 'ubuntu-latest'

# -----------------------------------------------------------------------------------------------------
# Security Automation Stage #910188
- name:  securityAutomationStagePool
  value: 'Azure Pipelines'
- name:  securityAutomationStageVmImage
  value: 'ubuntu-latest'

# -----------------------------------------------------------------------------------------------------
# Quality Automation Stage #910188
- name:  qaAutomationStagePool
  value: 'Azure Pipelines'
- name:  qaAutomationStageVmImage
  value: 'ubuntu-latest'

# -----------------------------------------------------------------------------------------------------
# Quality Automation Stage #910188
- name:  preProdAutomationStagePool
  value: 'Azure Pipelines'
- name:  preProdAutomationStageVmImage
  value: 'ubuntu-latest'

# -----------------------------------------------------------------------------------------------------
# @@END: SKULL-AND-CROSS BONES AREA
# Introduced with version blueprintVersion 2.1.1
# -----------------------------------------------------------------------------------------------------